//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace consultarGym.wsGym {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsGymSoap", Namespace="http://tempuri.org/")]
    public partial class wsGym : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarPaquetesOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarDetalleInscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarClientePorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarTipoInscripcionPorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarAdministradorPorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarEntrenadorPorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarDisciplinaPorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarNotaInscripcionPorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarPaquetesOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarDetalleInscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarTipoInscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarNotaInscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarAdministradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarEntrenadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarHorarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarDisciplinaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarVentaPorFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarDisciplinaPorPaqueteOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarInscripcionPorFechaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsGym() {
            this.Url = global::consultarGym.Properties.Settings.Default.consultarGym_wsGym_wsGym;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarPaquetesCompletedEventHandler buscarPaquetesCompleted;
        
        /// <remarks/>
        public event buscarClienteCompletedEventHandler buscarClienteCompleted;
        
        /// <remarks/>
        public event buscarDetalleInscripcionCompletedEventHandler buscarDetalleInscripcionCompleted;
        
        /// <remarks/>
        public event buscarClientePorNombreCompletedEventHandler buscarClientePorNombreCompleted;
        
        /// <remarks/>
        public event buscarTipoInscripcionPorNombreCompletedEventHandler buscarTipoInscripcionPorNombreCompleted;
        
        /// <remarks/>
        public event buscarAdministradorPorNombreCompletedEventHandler buscarAdministradorPorNombreCompleted;
        
        /// <remarks/>
        public event buscarEntrenadorPorNombreCompletedEventHandler buscarEntrenadorPorNombreCompleted;
        
        /// <remarks/>
        public event buscarHorarioCompletedEventHandler buscarHorarioCompleted;
        
        /// <remarks/>
        public event buscarDisciplinaPorNombreCompletedEventHandler buscarDisciplinaPorNombreCompleted;
        
        /// <remarks/>
        public event buscarNotaInscripcionPorNombreCompletedEventHandler buscarNotaInscripcionPorNombreCompleted;
        
        /// <remarks/>
        public event guardarPaquetesCompletedEventHandler guardarPaquetesCompleted;
        
        /// <remarks/>
        public event guardarDetalleInscripcionCompletedEventHandler guardarDetalleInscripcionCompleted;
        
        /// <remarks/>
        public event guardarClienteCompletedEventHandler guardarClienteCompleted;
        
        /// <remarks/>
        public event guardarTipoInscripcionCompletedEventHandler guardarTipoInscripcionCompleted;
        
        /// <remarks/>
        public event guardarNotaInscripcionCompletedEventHandler guardarNotaInscripcionCompleted;
        
        /// <remarks/>
        public event guardarAdministradorCompletedEventHandler guardarAdministradorCompleted;
        
        /// <remarks/>
        public event guardarEntrenadorCompletedEventHandler guardarEntrenadorCompleted;
        
        /// <remarks/>
        public event guardarHorarioCompletedEventHandler guardarHorarioCompleted;
        
        /// <remarks/>
        public event guardarDisciplinaCompletedEventHandler guardarDisciplinaCompleted;
        
        /// <remarks/>
        public event buscarVentaPorFechaCompletedEventHandler buscarVentaPorFechaCompleted;
        
        /// <remarks/>
        public event buscarDisciplinaPorPaqueteCompletedEventHandler buscarDisciplinaPorPaqueteCompleted;
        
        /// <remarks/>
        public event buscarInscripcionPorFechaCompletedEventHandler buscarInscripcionPorFechaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPaquetes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarPaquetes(string paquetes) {
            object[] results = this.Invoke("buscarPaquetes", new object[] {
                        paquetes});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPaquetesAsync(string paquetes) {
            this.buscarPaquetesAsync(paquetes, null);
        }
        
        /// <remarks/>
        public void buscarPaquetesAsync(string paquetes, object userState) {
            if ((this.buscarPaquetesOperationCompleted == null)) {
                this.buscarPaquetesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPaquetesOperationCompleted);
            }
            this.InvokeAsync("buscarPaquetes", new object[] {
                        paquetes}, this.buscarPaquetesOperationCompleted, userState);
        }
        
        private void OnbuscarPaquetesOperationCompleted(object arg) {
            if ((this.buscarPaquetesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPaquetesCompleted(this, new buscarPaquetesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarCliente(string paquetes) {
            object[] results = this.Invoke("buscarCliente", new object[] {
                        paquetes});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarClienteAsync(string paquetes) {
            this.buscarClienteAsync(paquetes, null);
        }
        
        /// <remarks/>
        public void buscarClienteAsync(string paquetes, object userState) {
            if ((this.buscarClienteOperationCompleted == null)) {
                this.buscarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarClienteOperationCompleted);
            }
            this.InvokeAsync("buscarCliente", new object[] {
                        paquetes}, this.buscarClienteOperationCompleted, userState);
        }
        
        private void OnbuscarClienteOperationCompleted(object arg) {
            if ((this.buscarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarClienteCompleted(this, new buscarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarDetalleInscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarDetalleInscripcion(string paquetes) {
            object[] results = this.Invoke("buscarDetalleInscripcion", new object[] {
                        paquetes});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarDetalleInscripcionAsync(string paquetes) {
            this.buscarDetalleInscripcionAsync(paquetes, null);
        }
        
        /// <remarks/>
        public void buscarDetalleInscripcionAsync(string paquetes, object userState) {
            if ((this.buscarDetalleInscripcionOperationCompleted == null)) {
                this.buscarDetalleInscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDetalleInscripcionOperationCompleted);
            }
            this.InvokeAsync("buscarDetalleInscripcion", new object[] {
                        paquetes}, this.buscarDetalleInscripcionOperationCompleted, userState);
        }
        
        private void OnbuscarDetalleInscripcionOperationCompleted(object arg) {
            if ((this.buscarDetalleInscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDetalleInscripcionCompleted(this, new buscarDetalleInscripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarClientePorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarClientePorNombre(string nombre) {
            object[] results = this.Invoke("buscarClientePorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarClientePorNombreAsync(string nombre) {
            this.buscarClientePorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarClientePorNombreAsync(string nombre, object userState) {
            if ((this.buscarClientePorNombreOperationCompleted == null)) {
                this.buscarClientePorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarClientePorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarClientePorNombre", new object[] {
                        nombre}, this.buscarClientePorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarClientePorNombreOperationCompleted(object arg) {
            if ((this.buscarClientePorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarClientePorNombreCompleted(this, new buscarClientePorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarTipoInscripcionPorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarTipoInscripcionPorNombre(string nombre) {
            object[] results = this.Invoke("buscarTipoInscripcionPorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarTipoInscripcionPorNombreAsync(string nombre) {
            this.buscarTipoInscripcionPorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarTipoInscripcionPorNombreAsync(string nombre, object userState) {
            if ((this.buscarTipoInscripcionPorNombreOperationCompleted == null)) {
                this.buscarTipoInscripcionPorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarTipoInscripcionPorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarTipoInscripcionPorNombre", new object[] {
                        nombre}, this.buscarTipoInscripcionPorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarTipoInscripcionPorNombreOperationCompleted(object arg) {
            if ((this.buscarTipoInscripcionPorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarTipoInscripcionPorNombreCompleted(this, new buscarTipoInscripcionPorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarAdministradorPorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarAdministradorPorNombre(string nombre) {
            object[] results = this.Invoke("buscarAdministradorPorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarAdministradorPorNombreAsync(string nombre) {
            this.buscarAdministradorPorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarAdministradorPorNombreAsync(string nombre, object userState) {
            if ((this.buscarAdministradorPorNombreOperationCompleted == null)) {
                this.buscarAdministradorPorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarAdministradorPorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarAdministradorPorNombre", new object[] {
                        nombre}, this.buscarAdministradorPorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarAdministradorPorNombreOperationCompleted(object arg) {
            if ((this.buscarAdministradorPorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarAdministradorPorNombreCompleted(this, new buscarAdministradorPorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarEntrenadorPorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarEntrenadorPorNombre(string nombre) {
            object[] results = this.Invoke("buscarEntrenadorPorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarEntrenadorPorNombreAsync(string nombre) {
            this.buscarEntrenadorPorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarEntrenadorPorNombreAsync(string nombre, object userState) {
            if ((this.buscarEntrenadorPorNombreOperationCompleted == null)) {
                this.buscarEntrenadorPorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarEntrenadorPorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarEntrenadorPorNombre", new object[] {
                        nombre}, this.buscarEntrenadorPorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarEntrenadorPorNombreOperationCompleted(object arg) {
            if ((this.buscarEntrenadorPorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarEntrenadorPorNombreCompleted(this, new buscarEntrenadorPorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarHorario(string hora) {
            object[] results = this.Invoke("buscarHorario", new object[] {
                        hora});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarHorarioAsync(string hora) {
            this.buscarHorarioAsync(hora, null);
        }
        
        /// <remarks/>
        public void buscarHorarioAsync(string hora, object userState) {
            if ((this.buscarHorarioOperationCompleted == null)) {
                this.buscarHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarHorarioOperationCompleted);
            }
            this.InvokeAsync("buscarHorario", new object[] {
                        hora}, this.buscarHorarioOperationCompleted, userState);
        }
        
        private void OnbuscarHorarioOperationCompleted(object arg) {
            if ((this.buscarHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarHorarioCompleted(this, new buscarHorarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarDisciplinaPorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarDisciplinaPorNombre(string nombre) {
            object[] results = this.Invoke("buscarDisciplinaPorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarDisciplinaPorNombreAsync(string nombre) {
            this.buscarDisciplinaPorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarDisciplinaPorNombreAsync(string nombre, object userState) {
            if ((this.buscarDisciplinaPorNombreOperationCompleted == null)) {
                this.buscarDisciplinaPorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDisciplinaPorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarDisciplinaPorNombre", new object[] {
                        nombre}, this.buscarDisciplinaPorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarDisciplinaPorNombreOperationCompleted(object arg) {
            if ((this.buscarDisciplinaPorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDisciplinaPorNombreCompleted(this, new buscarDisciplinaPorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarNotaInscripcionPorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarNotaInscripcionPorNombre(int nombre) {
            object[] results = this.Invoke("buscarNotaInscripcionPorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarNotaInscripcionPorNombreAsync(int nombre) {
            this.buscarNotaInscripcionPorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarNotaInscripcionPorNombreAsync(int nombre, object userState) {
            if ((this.buscarNotaInscripcionPorNombreOperationCompleted == null)) {
                this.buscarNotaInscripcionPorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarNotaInscripcionPorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarNotaInscripcionPorNombre", new object[] {
                        nombre}, this.buscarNotaInscripcionPorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarNotaInscripcionPorNombreOperationCompleted(object arg) {
            if ((this.buscarNotaInscripcionPorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarNotaInscripcionPorNombreCompleted(this, new buscarNotaInscripcionPorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarPaquetes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarPaquetes(string nombre, string descripcion, int cupos, int id_disciplina) {
            object[] results = this.Invoke("guardarPaquetes", new object[] {
                        nombre,
                        descripcion,
                        cupos,
                        id_disciplina});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarPaquetesAsync(string nombre, string descripcion, int cupos, int id_disciplina) {
            this.guardarPaquetesAsync(nombre, descripcion, cupos, id_disciplina, null);
        }
        
        /// <remarks/>
        public void guardarPaquetesAsync(string nombre, string descripcion, int cupos, int id_disciplina, object userState) {
            if ((this.guardarPaquetesOperationCompleted == null)) {
                this.guardarPaquetesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarPaquetesOperationCompleted);
            }
            this.InvokeAsync("guardarPaquetes", new object[] {
                        nombre,
                        descripcion,
                        cupos,
                        id_disciplina}, this.guardarPaquetesOperationCompleted, userState);
        }
        
        private void OnguardarPaquetesOperationCompleted(object arg) {
            if ((this.guardarPaquetesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarPaquetesCompleted(this, new guardarPaquetesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarDetalleInscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarDetalleInscripcion(int cantidad, int id_cliente, int precio, int id_paquete) {
            object[] results = this.Invoke("guardarDetalleInscripcion", new object[] {
                        cantidad,
                        id_cliente,
                        precio,
                        id_paquete});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarDetalleInscripcionAsync(int cantidad, int id_cliente, int precio, int id_paquete) {
            this.guardarDetalleInscripcionAsync(cantidad, id_cliente, precio, id_paquete, null);
        }
        
        /// <remarks/>
        public void guardarDetalleInscripcionAsync(int cantidad, int id_cliente, int precio, int id_paquete, object userState) {
            if ((this.guardarDetalleInscripcionOperationCompleted == null)) {
                this.guardarDetalleInscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarDetalleInscripcionOperationCompleted);
            }
            this.InvokeAsync("guardarDetalleInscripcion", new object[] {
                        cantidad,
                        id_cliente,
                        precio,
                        id_paquete}, this.guardarDetalleInscripcionOperationCompleted, userState);
        }
        
        private void OnguardarDetalleInscripcionOperationCompleted(object arg) {
            if ((this.guardarDetalleInscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarDetalleInscripcionCompleted(this, new guardarDetalleInscripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarCliente(string nombre, string apellido) {
            object[] results = this.Invoke("guardarCliente", new object[] {
                        nombre,
                        apellido});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarClienteAsync(string nombre, string apellido) {
            this.guardarClienteAsync(nombre, apellido, null);
        }
        
        /// <remarks/>
        public void guardarClienteAsync(string nombre, string apellido, object userState) {
            if ((this.guardarClienteOperationCompleted == null)) {
                this.guardarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarClienteOperationCompleted);
            }
            this.InvokeAsync("guardarCliente", new object[] {
                        nombre,
                        apellido}, this.guardarClienteOperationCompleted, userState);
        }
        
        private void OnguardarClienteOperationCompleted(object arg) {
            if ((this.guardarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarClienteCompleted(this, new guardarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarTipoInscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarTipoInscripcion(string nombre, int costo, string periodo, int frecuencia) {
            object[] results = this.Invoke("guardarTipoInscripcion", new object[] {
                        nombre,
                        costo,
                        periodo,
                        frecuencia});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarTipoInscripcionAsync(string nombre, int costo, string periodo, int frecuencia) {
            this.guardarTipoInscripcionAsync(nombre, costo, periodo, frecuencia, null);
        }
        
        /// <remarks/>
        public void guardarTipoInscripcionAsync(string nombre, int costo, string periodo, int frecuencia, object userState) {
            if ((this.guardarTipoInscripcionOperationCompleted == null)) {
                this.guardarTipoInscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarTipoInscripcionOperationCompleted);
            }
            this.InvokeAsync("guardarTipoInscripcion", new object[] {
                        nombre,
                        costo,
                        periodo,
                        frecuencia}, this.guardarTipoInscripcionOperationCompleted, userState);
        }
        
        private void OnguardarTipoInscripcionOperationCompleted(object arg) {
            if ((this.guardarTipoInscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarTipoInscripcionCompleted(this, new guardarTipoInscripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarNotaInscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarNotaInscripcion(int idCli, int idTipoIns, string fecha) {
            object[] results = this.Invoke("guardarNotaInscripcion", new object[] {
                        idCli,
                        idTipoIns,
                        fecha});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarNotaInscripcionAsync(int idCli, int idTipoIns, string fecha) {
            this.guardarNotaInscripcionAsync(idCli, idTipoIns, fecha, null);
        }
        
        /// <remarks/>
        public void guardarNotaInscripcionAsync(int idCli, int idTipoIns, string fecha, object userState) {
            if ((this.guardarNotaInscripcionOperationCompleted == null)) {
                this.guardarNotaInscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarNotaInscripcionOperationCompleted);
            }
            this.InvokeAsync("guardarNotaInscripcion", new object[] {
                        idCli,
                        idTipoIns,
                        fecha}, this.guardarNotaInscripcionOperationCompleted, userState);
        }
        
        private void OnguardarNotaInscripcionOperationCompleted(object arg) {
            if ((this.guardarNotaInscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarNotaInscripcionCompleted(this, new guardarNotaInscripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarAdministrador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarAdministrador(string nombre, string apellido, string contrasena) {
            object[] results = this.Invoke("guardarAdministrador", new object[] {
                        nombre,
                        apellido,
                        contrasena});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarAdministradorAsync(string nombre, string apellido, string contrasena) {
            this.guardarAdministradorAsync(nombre, apellido, contrasena, null);
        }
        
        /// <remarks/>
        public void guardarAdministradorAsync(string nombre, string apellido, string contrasena, object userState) {
            if ((this.guardarAdministradorOperationCompleted == null)) {
                this.guardarAdministradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarAdministradorOperationCompleted);
            }
            this.InvokeAsync("guardarAdministrador", new object[] {
                        nombre,
                        apellido,
                        contrasena}, this.guardarAdministradorOperationCompleted, userState);
        }
        
        private void OnguardarAdministradorOperationCompleted(object arg) {
            if ((this.guardarAdministradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarAdministradorCompleted(this, new guardarAdministradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarEntrenador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarEntrenador(string nombre, string apellido) {
            object[] results = this.Invoke("guardarEntrenador", new object[] {
                        nombre,
                        apellido});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarEntrenadorAsync(string nombre, string apellido) {
            this.guardarEntrenadorAsync(nombre, apellido, null);
        }
        
        /// <remarks/>
        public void guardarEntrenadorAsync(string nombre, string apellido, object userState) {
            if ((this.guardarEntrenadorOperationCompleted == null)) {
                this.guardarEntrenadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarEntrenadorOperationCompleted);
            }
            this.InvokeAsync("guardarEntrenador", new object[] {
                        nombre,
                        apellido}, this.guardarEntrenadorOperationCompleted, userState);
        }
        
        private void OnguardarEntrenadorOperationCompleted(object arg) {
            if ((this.guardarEntrenadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarEntrenadorCompleted(this, new guardarEntrenadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarHorario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarHorario(string horaE, string horaS) {
            object[] results = this.Invoke("guardarHorario", new object[] {
                        horaE,
                        horaS});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarHorarioAsync(string horaE, string horaS) {
            this.guardarHorarioAsync(horaE, horaS, null);
        }
        
        /// <remarks/>
        public void guardarHorarioAsync(string horaE, string horaS, object userState) {
            if ((this.guardarHorarioOperationCompleted == null)) {
                this.guardarHorarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarHorarioOperationCompleted);
            }
            this.InvokeAsync("guardarHorario", new object[] {
                        horaE,
                        horaS}, this.guardarHorarioOperationCompleted, userState);
        }
        
        private void OnguardarHorarioOperationCompleted(object arg) {
            if ((this.guardarHorarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarHorarioCompleted(this, new guardarHorarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/guardarDisciplina", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet guardarDisciplina(string nombre, string descripcion, int idE, int idH) {
            object[] results = this.Invoke("guardarDisciplina", new object[] {
                        nombre,
                        descripcion,
                        idE,
                        idH});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void guardarDisciplinaAsync(string nombre, string descripcion, int idE, int idH) {
            this.guardarDisciplinaAsync(nombre, descripcion, idE, idH, null);
        }
        
        /// <remarks/>
        public void guardarDisciplinaAsync(string nombre, string descripcion, int idE, int idH, object userState) {
            if ((this.guardarDisciplinaOperationCompleted == null)) {
                this.guardarDisciplinaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarDisciplinaOperationCompleted);
            }
            this.InvokeAsync("guardarDisciplina", new object[] {
                        nombre,
                        descripcion,
                        idE,
                        idH}, this.guardarDisciplinaOperationCompleted, userState);
        }
        
        private void OnguardarDisciplinaOperationCompleted(object arg) {
            if ((this.guardarDisciplinaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarDisciplinaCompleted(this, new guardarDisciplinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarVentaPorFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarVentaPorFecha(string fecha1, string fecha2) {
            object[] results = this.Invoke("buscarVentaPorFecha", new object[] {
                        fecha1,
                        fecha2});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarVentaPorFechaAsync(string fecha1, string fecha2) {
            this.buscarVentaPorFechaAsync(fecha1, fecha2, null);
        }
        
        /// <remarks/>
        public void buscarVentaPorFechaAsync(string fecha1, string fecha2, object userState) {
            if ((this.buscarVentaPorFechaOperationCompleted == null)) {
                this.buscarVentaPorFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarVentaPorFechaOperationCompleted);
            }
            this.InvokeAsync("buscarVentaPorFecha", new object[] {
                        fecha1,
                        fecha2}, this.buscarVentaPorFechaOperationCompleted, userState);
        }
        
        private void OnbuscarVentaPorFechaOperationCompleted(object arg) {
            if ((this.buscarVentaPorFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarVentaPorFechaCompleted(this, new buscarVentaPorFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarDisciplinaPorPaquete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarDisciplinaPorPaquete(string nombre) {
            object[] results = this.Invoke("buscarDisciplinaPorPaquete", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarDisciplinaPorPaqueteAsync(string nombre) {
            this.buscarDisciplinaPorPaqueteAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarDisciplinaPorPaqueteAsync(string nombre, object userState) {
            if ((this.buscarDisciplinaPorPaqueteOperationCompleted == null)) {
                this.buscarDisciplinaPorPaqueteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDisciplinaPorPaqueteOperationCompleted);
            }
            this.InvokeAsync("buscarDisciplinaPorPaquete", new object[] {
                        nombre}, this.buscarDisciplinaPorPaqueteOperationCompleted, userState);
        }
        
        private void OnbuscarDisciplinaPorPaqueteOperationCompleted(object arg) {
            if ((this.buscarDisciplinaPorPaqueteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDisciplinaPorPaqueteCompleted(this, new buscarDisciplinaPorPaqueteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarInscripcionPorFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarInscripcionPorFecha(string fecha1, string fecha2) {
            object[] results = this.Invoke("buscarInscripcionPorFecha", new object[] {
                        fecha1,
                        fecha2});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarInscripcionPorFechaAsync(string fecha1, string fecha2) {
            this.buscarInscripcionPorFechaAsync(fecha1, fecha2, null);
        }
        
        /// <remarks/>
        public void buscarInscripcionPorFechaAsync(string fecha1, string fecha2, object userState) {
            if ((this.buscarInscripcionPorFechaOperationCompleted == null)) {
                this.buscarInscripcionPorFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarInscripcionPorFechaOperationCompleted);
            }
            this.InvokeAsync("buscarInscripcionPorFecha", new object[] {
                        fecha1,
                        fecha2}, this.buscarInscripcionPorFechaOperationCompleted, userState);
        }
        
        private void OnbuscarInscripcionPorFechaOperationCompleted(object arg) {
            if ((this.buscarInscripcionPorFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarInscripcionPorFechaCompleted(this, new buscarInscripcionPorFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarPaquetesCompletedEventHandler(object sender, buscarPaquetesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPaquetesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPaquetesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarClienteCompletedEventHandler(object sender, buscarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarDetalleInscripcionCompletedEventHandler(object sender, buscarDetalleInscripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDetalleInscripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDetalleInscripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarClientePorNombreCompletedEventHandler(object sender, buscarClientePorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarClientePorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarClientePorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarTipoInscripcionPorNombreCompletedEventHandler(object sender, buscarTipoInscripcionPorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarTipoInscripcionPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarTipoInscripcionPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarAdministradorPorNombreCompletedEventHandler(object sender, buscarAdministradorPorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarAdministradorPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarAdministradorPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarEntrenadorPorNombreCompletedEventHandler(object sender, buscarEntrenadorPorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarEntrenadorPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarEntrenadorPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarHorarioCompletedEventHandler(object sender, buscarHorarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarHorarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarHorarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarDisciplinaPorNombreCompletedEventHandler(object sender, buscarDisciplinaPorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDisciplinaPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDisciplinaPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarNotaInscripcionPorNombreCompletedEventHandler(object sender, buscarNotaInscripcionPorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarNotaInscripcionPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarNotaInscripcionPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarPaquetesCompletedEventHandler(object sender, guardarPaquetesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarPaquetesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarPaquetesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarDetalleInscripcionCompletedEventHandler(object sender, guardarDetalleInscripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarDetalleInscripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarDetalleInscripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarClienteCompletedEventHandler(object sender, guardarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarTipoInscripcionCompletedEventHandler(object sender, guardarTipoInscripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarTipoInscripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarTipoInscripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarNotaInscripcionCompletedEventHandler(object sender, guardarNotaInscripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarNotaInscripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarNotaInscripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarAdministradorCompletedEventHandler(object sender, guardarAdministradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarAdministradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarAdministradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarEntrenadorCompletedEventHandler(object sender, guardarEntrenadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarEntrenadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarEntrenadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarHorarioCompletedEventHandler(object sender, guardarHorarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarHorarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarHorarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void guardarDisciplinaCompletedEventHandler(object sender, guardarDisciplinaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarDisciplinaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarDisciplinaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarVentaPorFechaCompletedEventHandler(object sender, buscarVentaPorFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarVentaPorFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarVentaPorFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarDisciplinaPorPaqueteCompletedEventHandler(object sender, buscarDisciplinaPorPaqueteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDisciplinaPorPaqueteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDisciplinaPorPaqueteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarInscripcionPorFechaCompletedEventHandler(object sender, buscarInscripcionPorFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarInscripcionPorFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarInscripcionPorFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591